# Generated by Django 2.2.5 on 2020-11-10 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ffmpeg', '0005_py3_fixes'),
    ]

    operations = [
        migrations.AddField(
            model_name='convertingcommand',
            name='title',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Title'),
        ),
    ]
